services:
  api:
    container_name: cbio-ingest-api
    image: ghcr.io/bihealth/cbio-ingest:latest
    env_file:
      - .env.cbio-ingest
    depends_on:
      - redis
    volumes:
      - ./study:/app/study:ro
      - ./panel:/app/panel:ro
      - ./db:/db
    networks:
      - cbio-ingest-net

  worker:
    container_name: cbio-ingest-worker
    image: ghcr.io/bihealth/cbio-ingest:latest
    command: ["rq", "worker", "--with-scheduler"]
    env_file:
      - .env.cbio-ingest
    depends_on:
      - redis
    volumes:
      - ./study:/app/study:ro
      - ./panel:/app/panel:ro
      - ./db:/db
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - cbio-ingest-net

  redis:
    container_name: cbio-ingest-redis
    image: redis:7-alpine
    volumes:
      - cbio-ingest-redis-data:/data
    networks:
      - cbio-ingest-net
    command: redis-server --appendonly yes

volumes:
  cbio-ingest-redis-data:

networks:
  cbio-ingest-net:
