"""initial migration

Revision ID: 4ec2e5522283
Revises:
Create Date: 2026-06-17 11:58:14.678496

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlmodel.sql.sqltypes import AutoString

# revision identifiers, used by Alembic.
revision: str = "4ec2e5522283"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "panel",
        sa.Column("name", AutoString(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("INITIAL", "IN_PROGRESS", "COMPLETED", "FAILED", name="status"),
            nullable=False,
        ),
        sa.Column("date", sa.DateTime(), nullable=True),
        sa.Column("logs", sa.JSON(), nullable=False),
        sa.Column("job_id", AutoString(), nullable=True),
        sa.Column("command", AutoString(), nullable=True),
        sa.Column("cbioportal_version", AutoString(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "study",
        sa.Column("name", AutoString(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("INITIAL", "IN_PROGRESS", "COMPLETED", "FAILED", name="status"),
            nullable=False,
        ),
        sa.Column("date", sa.DateTime(), nullable=True),
        sa.Column("logs", sa.JSON(), nullable=False),
        sa.Column("job_id", AutoString(), nullable=True),
        sa.Column("command", AutoString(), nullable=True),
        sa.Column("cbioportal_version", AutoString(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "validation",
        sa.Column("name", AutoString(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("INITIAL", "IN_PROGRESS", "COMPLETED", "FAILED", name="status"),
            nullable=False,
        ),
        sa.Column("date", sa.DateTime(), nullable=True),
        sa.Column("logs", sa.JSON(), nullable=False),
        sa.Column("job_id", AutoString(), nullable=True),
        sa.Column("command", AutoString(), nullable=True),
        sa.Column("cbioportal_version", AutoString(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("study_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["study_id"],
            ["study.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("validation")
    op.drop_table("study")
    op.drop_table("panel")
    # ### end Alembic commands ###
