"""added date_created field to models

Revision ID: 209dc4982f7e
Revises: 55f23824495c
Create Date: 2026-05-22 09:47:20.475070

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "209dc4982f7e"
down_revision: Union[str, Sequence[str], None] = "55f23824495c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "panel",
        sa.Column(
            "date_created",
            sa.DateTime(),
            nullable=False,
            server_default=sa.text("'1970-01-01 00:00:00'"),
        ),
    )
    op.add_column(
        "study",
        sa.Column(
            "date_created",
            sa.DateTime(),
            nullable=False,
            server_default=sa.text("'1970-01-01 00:00:00'"),
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("study", "date_created")
    op.drop_column("panel", "date_created")
    # ### end Alembic commands ###
