"""initial schema

Revision ID: 55f23824495c
Revises:
Create Date: 2026-05-08 07:56:19.121568

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "55f23824495c"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
