name: Setup Project with Python and UV

runs:
  using: composite

  steps:
    - uses: actions/setup-python@v6
      with:
        python-version: "3.12"

    - uses: astral-sh/setup-uv@v6

    - run: uv sync --frozen --dev
      shell: bash